SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[cliente](
    [idCliente] [int] NOT NULL,
    [nombre] [varchar](100) NULL,
    [estado] [tinyint] NULL,
    [idUsuario] [int] NULL,
    PRIMARY KEY CLUSTERED ([idCliente] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];
GO
